version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: slt_credentials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: >
      sh -c "until pg_isready -h db -p 5432 -U postgres; do echo 'Waiting for database...'; sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - ENCRYPTION_KEY=your-32-character-encryption-key-here
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    ports:
      - "9000:80"
    depends_on:
      - backend



volumes:
  postgres_data:
