# Generated by Django 5.2.14 on 2026-05-29 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_credential_auto_rotate_credential_last_rotated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='encrypted_password',
            new_name='encrypted_secret',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='rotation_interval_days',
            new_name='rotation_period_days',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='auto_rotate',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='url',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='access_duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(default='LEGACY_ACTION', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.credential'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='credential_type',
            field=models.CharField(choices=[('PASSWORD', 'Password'), ('API_KEY', 'API Key'), ('SSH_KEY', 'SSH Key'), ('CERTIFICATE', 'Certificate')], default='PASSWORD', max_length=50),
        ),
        migrations.AddField(
            model_name='credential',
            name='is_approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='next_rotation_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='secret_iv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='target_url_or_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='criticality_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('MISSION_CRITICAL', 'Mission Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='slt_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='credential',
            name='last_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('SECOPS', 'SecOps'), ('MANAGER', 'Project Manager'), ('DEVELOPER', 'Developer'), ('READONLY', 'Read Only')], default='DEVELOPER', max_length=20),
        ),
    ]
